name: Pmon Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Compilar proyecto y tests
      run: make build

    - name: Ejecutar los tests
      run: make test
